// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_authorization.cpp"
#include "EWIEGA46WW/moc_confectionery.cpp"
#include "EWIEGA46WW/moc_confectionerystoreinformationsystem.cpp"
#include "EWIEGA46WW/moc_historyoforders.cpp"
#include "EWIEGA46WW/moc_myorder.cpp"
#include "EWIEGA46WW/moc_registration.cpp"
#include "EWIEGA46WW/moc_userdatabase.cpp"
